push/pull images from registry

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,26 +8,49 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Login to Docker Registry
+          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
+      - run:
+          name: Setup Env Variables
+          command: echo 'export CI_BRANCH=":$CIRCLE_BRANCH"' >> $BASH_ENV
+      - run:
+          name: Pull Images
+          # this always seems to fail and pull from master
+          command: |
+            pull_status=$(docker-compose pull --quiet; echo $?)
+            if [ $pull_status -ne 0 ]; then
+              echo "[INFO] No images exist for this tag, pulling from master branch instead"
+              current_branch=$CIRCLE_BRANCH
+              export CI_BRANCH=":master"
+              docker-compose pull --ignore-pull-failures
+            fi
+      - run:
           name: Build
           command: docker-compose build
-
-  migrate:
-    machine: true
-    working_directory: ~/repo
-    steps:
-      - checkout
       - run:
-          name: Make migrations
-          command: docker-compose run --rm django python manage.py makemigrations
-      - run:
-          name: Migrate
-          command: docker-compose run --rm django python manage.py migrate
+          name: Push Images
+          command: docker-compose push
 
   test:
     machine: true
     working_directory: ~/repo
     steps:
       - checkout
+      - run:
+          name: Login to Docker Registry
+          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
+      - run:
+          name: Setup Env Variables
+          command: echo 'export CI_BRANCH=":$CIRCLE_BRANCH"' >> $BASH_ENV
+      - run:
+          name: Pull Images
+          command: docker-compose pull
+      - run:
+          name: Bring up dependency containers
+          command: docker-compose run --rm start_dependencies
+      - run:
+          name: Migrate
+          command: docker-compose run --rm django python manage.py migrate
       - run:
           name: pytest
           command: make pytest-ci
@@ -48,9 +71,6 @@ workflows:
   build_and_test:
     jobs:
       - build
-      - migrate:
-          requires:
-            - build
       - test:
           requires:
-            - migrate
+            - build
